import type { Metadata } from "next";
import "./globals.css";
import { Inter, Press_Start_2P, Silkscreen, VT323, Nunito } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], weight: ['100','400','700','900'], variable: "--font-inter" });
const pressStart = Press_Start_2P({ subsets: ['latin'], weight: '400', variable: "--font-pressStart" });
const silkscreen = Silkscreen({ subsets: ['latin'], weight: ['400','700'], variable: "--font-silkscreen" });
const vt323 = VT323({ subsets: ['latin'], weight: '400', variable: "--font-vt323" });
const nunito = Nunito({ subsets: ["latin"], weight: "400", variable: "--font-nunito" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${silkscreen.variable} ${inter.variable} ${pressStart.variable} ${vt323.variable} ${nunito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}